//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalaryCalculation.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Employee
    {
        [Required]
        public int EmployeeId { get; set; }

        [Required]
        [Display(Name = "User Name")]
        [StringLength(20, ErrorMessage = "Your name has more than 20 characters")]
        public string Name { get; set; }

        [Required]
        public string Lastname { get; set; }

        [Required]
        public string Address { get; set; }
        public decimal NetSalary { get; set; }
        public decimal BrutSalary { get; set; }
    }
}
